name: Lint and Format Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      # This action installs Poetry AND adds it to the PATH correctly
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          
      - name: Install dependencies with Poetry
        run: poetry install --no-interaction --no-root
        
      - name: Show Poetry environment (debug)
        run: poetry env info
        
      - name: Install lint/format tools
        run: poetry run pip install flake8 black
        
      - name: Run flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Run black (check only)
        run: poetry run black --check .
