name: Python Repricing Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl customtkinter plyer xlsxwriter

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --ignore=E501,F401

    - name: Run placeholder test (optional)
      run: |
        echo "No tests yet. Add them later under /tests"