name: Weekly File Sync

on:
  schedule:
    - cron: '0 10 * * 5'  # Every Friday at 10:00 AM UTC (6:00 AM ET)

jobs:
  sync-specific-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination repo
        uses: actions/checkout@v3

      - name: Add upstream (source repo)
        run: |
          git remote add upstream https://github.com/UWDataTrx/GitHub.git
          git fetch upstream

      - name: Sync specific files
        run: |
          FILES="app.py tier_disruption.py openmdf_bg.py openmdf_tier.py bg_disruption.py epls_lbl.py merge.py sharx_lbl.py utils.py"
          for file in $FILES; do
            git checkout upstream/main -- $file
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Weekly sync of specific files"
          git push origin main
        continue-on-error: true  # Don't fail if no changes
